MessFinder/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path
from MainApp import views

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", views.shome, name="shome"),
    path("home/<int:id>", views.home, name="home"),
    path("shome", views.shome, name="shome"),

    path("register", views.register, name="register"),
    path("register/student", views.StudentRegister, name="studentregister"),
    path("register/owner", views.OwnerRegister, name="ownerregister"),

    path('edit_sprofile/<int:id>', views.edit_sprofile, name = 'edit_sprofile'),
    path('edit_oprofile/<int:id>', views.edit_oprofile, name = 'edit_oprofile'),
    

    path("login", views.loginpage, name="login"),
    path("logout", views.logoutpage, name="logout"),
  
    path("ohome/<int:id>", views.ohome, name="ohome"),
    path("oprofile/<int:id>", views.oprofile, name="oprofile"),
    
    path("profile/<int:id>", views.profile, name="profile"),

    path("room/<int:id>", views.room_details, name="room_details"),
    path("update_room/<int:id>", views.update_room, name="update_room"),
    path("delete_room/<int:id>", views.delete_room, name="delete_room"),
    path("add_room/<int:id>", views.add_room, name="add_room"),
    path("comment", views.comment, name="comment"),
    
    path('add_mess/<int:id>', views.add_mess, name = 'add_mess'),
    path("mess/<int:id>", views.mess_details, name="mess_details"),
    path('all_mess', views.results, name='all_mess'),
    path("results", views.results, name="results"),
    path("review", views.review, name="review"),
    path('edit_mess/<int:id>', views.edit_mess, name = 'edit_mess'),
    path('delete_mess/<int:id>', views.delete_mess, name = 'delete_mess'),
    
    
    # path("sprofile/<int:sid>", views.sprofile, name = sprofile),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainApp/models.py
import email
from distutils.command.upload import upload
from random import choices

from django.contrib.auth.models import (AbstractBaseUser, AbstractUser,
                                        BaseUserManager, PermissionsMixin)
from django.db import models
from django.utils import timezone

# from platformdirs import site_data_dir
# from pyparsing import makeXMLTags
# from django.utils.translation import ugettext_lazy as _
# from django.utils.translation import gettext as _
# # Create your models here.


# class CustomUser(AbstractUser):
#     username = None
#     email = models.EmailField(_)


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError("Users must have an email address")
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user = self._create_user(email, password, True, True, **extra_fields)
        user.save(using=self._db)
        return user

from random import randint


class CustomUser(AbstractBaseUser, PermissionsMixin):


    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254)
    number = models.CharField(max_length=14)
    profile_pic = models.ImageField(blank=True, upload_to="profile/", default="profile/pro_pic.jpg")

    is_student = models.BooleanField(default=0)  # 1 for student, 0 for owner

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []
    print("ok")
    objects = CustomUserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

    def get_email(self):
        return self.email

    def __str__(self):
        return str(self.email)


class Student(models.Model):
    department_choices = (
        (2, "CSE"),
        (3, "EEE"),
        (4, "ECE"),
        (1, "Agriculture"),
        (5, "DVM"),
        (6, "Physics"),
    )
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    sid = models.IntegerField(primary_key=True)
    department = models.IntegerField(choices=department_choices)

    id_card_pic = models.ImageField(blank=True)

    fb_profile = models.URLField(blank=True)

    def __str__(self):
        return self.user.name


class Owner(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)

    nid_card_pic = models.ImageField()

    def __str__(self):
        return self.user.name


class Mess(models.Model):

    region_choices = ((1, "Mohabolipur"), (2, "Suvra"), (3, "Kornai"), (4, "BKSP"))
    gender_choices = ((1, "Male"), (0, "Female"))
    cooking_system_choices = ((1, "Meal"), (2, "Bati"), (3, "On Your Own"))
    structure_choices = ((1, "Multi-storey"), (2, "Single-storey"), (3, "Tin Shed"))

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    region = models.IntegerField(choices=region_choices)
    gender = models.IntegerField(choices=gender_choices)
    meal_system = models.IntegerField(choices=cooking_system_choices)
    structure = models.IntegerField(choices=structure_choices)
    students_num = models.IntegerField()
    distance = models.IntegerField()  # in meter
    address = models.CharField(max_length=500, default="Default Mess Address")
    image1 = models.ImageField(upload_to="Room_Gallery", null=True)
    image2 = models.ImageField(upload_to="Room_Gallery", null=True)
    image3 = models.ImageField(upload_to="Room_Gallery", null=True)

    def __str__(self):
        return self.name


# class MessImages(models.Model):
#     mess        = models.ForeignKey(Mess, on_delete=models.CASCADE)
#     image       = models.FileField(upload_to='Mess_Gallery')

#     def __str__(self):
#         return self.mess.name


class Room(models.Model):
    bed_num_choice = ((1, 1), (2, 2), (3, 3), (4, 4))
    status_choice = ((0, "Not Available"), (1, "Available"))

    id = models.AutoField(primary_key=True)
    room_no = models.IntegerField()
    bed_num = models.IntegerField(choices=bed_num_choice)
    mess = models.ForeignKey(Mess, on_delete=models.CASCADE)
    price = models.IntegerField()
    floor = models.IntegerField(default=0)
    status = models.BooleanField(default=1)
    image1 = models.ImageField(upload_to="Room_Gallery", null=True)
    image2 = models.ImageField(upload_to="Room_Gallery", null=True)
    image3 = models.ImageField(upload_to="Room_Gallery", null=True)

    def __str__(self):
        return str(self.room_no)


# class RoomImages(models.Model):
#     room        = models.ForeignKey(Room, on_delete=models.CASCADE)
#     image1       =models.FileField(upload_to='Room_Gallery')
#     image2       =models.FileField(upload_to='Room_Gallery')
#     image2       =models.FileField(upload_to='Room_Gallery')

#     def __str__(self):
#         return self.room.mess.name + " - " + str(self.room.room_no)


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField()
    commenter = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    # updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.content[:10]


class Review(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField()
    reviewer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    mess = models.ForeignKey(Mess, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.content[:10]

templates/add_mess.html
{%extends 'base.html'%}
{%load static%}
{%block head%}
<link type="text/css" rel="stylesheet" href="{% static 'css/update_room.css' %}" />
{%endblock head%}
 {%block title%}
 Edit Mess 
{%endblock title%}

{%block content%}
<div class="container-fluid text-center booking-form">
    <form method='POST' class="edit-form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1>Add Mess</h1>
                    <hr>
                </div>
                <div class="col">
                    <div class="form-group">
                        <span class="form-label">Name</span>
                        {{messform.name}}
                    </div>
                    <div class="form-group">
                        <span class="form-label">Gender</span>
                        {{messform.gender}}
                    </div>

                    <div class="form-group">
                        <span class="form-label">Meal System</span>
                        {{messform.meal_system}}
                    </div>
                    <div class="form-group">
                        <span class="form-label">Region</span>
                        {{messform.region}}
                    </div>
                    <div class="form-group">
                        <span class="form-label">Structure</span>
                        {{messform.structure}}
                    </div>
                    <div class="form-group">
                        <span class="form-label">Students capacity</span>
                        {{messform.students_num}}
                    </div>
                    <div class="form-group">
                        <span class="form-label">distance in meter from Main gate</span>
                        {{messform.distance}}
                    </div>
                    <div class="form-group">
                        <span class="form-label">address</span>
                        {{messform.address}}
                    </div>
                    {{messform.image1}}
                    {{messform.image2}}
                    {{messform.image3}}
                    <!-- {{messform.mess}} -->
                    <div class="form-btn">
                        <input type="submit" value="Add" class="submit-btn">
                    </div>



                </div>

            </div>
        </div>

    </form>
</div>
{% block script%}
<script>
    element = document.querySelectorAll("input, select");
    // element = element + document.getElementsByTagName("select");

    console.log(element);
    for (var i = 0; i < element.length -1; i++) {
        element[i].classList.add('form-control');
    }
    element[element.length - 1].classList.add('form-checkbox');
</script>
{% endblock script %}
{%endblock content%}

templates/details.html
{%extends 'base.html'%}
{% load static%}

{%block title%}
Room Details
{%endblock title%}

{%block head%}



<link type="text/css" rel="stylesheet" href="{% static 'css/details.css'  %}" />
{%endblock head%}



{%block content%}


<div class="container">
    <div class="col-lg-8 border p-3 main-section bg-white">
        <div class="row hedding m-0 pl-3 pt-0 pb-3">
            <a href="/mess/{{room.mess.id}}">
                <h2>{{room.mess.name }}</h2>
            </a>
        </div>
        <div class="row m-0">
            <div class="col-lg-4 left-side-product-box pb-3">
                <img src="{{room.image1.url}}" class="border p-3">
                <span class="sub-img">
                    <img src="{{room.image2.url}}" class="border p-2">
                    <img src="{{room.image3.url}}" class="border p-2">

                </span>
            </div>
            <div class="col-lg-8">
                <div class="right-side-pro-detail border p-3 m-0">
                    <div class="row">
                        <div class="col-lg-12">
                            <span></span>
                            <p class="m-0 p-0">Room No. {{room.room_no}}</p>
                        </div>
                        <div class="col-lg-12">
                            <p class="m-0 p-0 price-pro">৳{{room.price}} per bed</p>
                            <hr class="p-0 m-0">
                        </div>
                        <div class="col-lg-12 pt-2">
                            <h5>Room Detail:</h5>
                            <div class="row">
                                <div class="col left-col">

                                    <span class="">{{room.bed_num}} beds</span> <br>

                                    <span class="">{{room.floor}} Floor</span> <br>
                                    <span class="region">For {{room.mess.get_gender_display}} </span> <br>
                                    {% if room.status%}
                                    <span style="color: rgb(0, 126, 82);">Available</span> <br>
                                    {% else %}
                                    <span style="color: rgb(219, 56, 15);">Unvailable</span> <br>
                                    {% endif%}
                                </div>
                                <div class="col ">


                                    <span class="">{{room.mess.get_region_display}} area</span> <br>
                                    <span class="">Meal System: {{room.mess.get_cooking_system_display}}</span> <br>


                                    <span>Structure: {{room.mess.get_structure_display}}</span> <br>

                                    <span>{{room.mess.students_num}} students</span> <br>
                                    <span>{{room.mess.distance}} meters</span> <br>
                                </div>
                            </div>
                            <!-- -->
                        </div>



                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center pt-3">
                <h4>Reviews:</h4>
                <!-- TODO: Differentiate Mess Comments and Room Comments -->
            </div>
        </div>
        {% for comment in comments %}
        <div class="row my-1">
            <div class="room-comment col-lg-12 py-1">
                <span class='username'>{{comment.user.name}}</span> <br>
                {{comment.content}}
                <hr>

            </div>

        </div>
        {%endfor%}
    </div>
</div>
{%endblock content%}

templates/mess_details.html
{%extends 'base.html'%}
{%load static%}
{%block head%}
<link type="text/css" rel="stylesheet" href="{% static 'css/details.css'  %}" />
<link type="text/css" rel="stylesheet" href="{% static 'css/mess_details.css' %}" />


{%endblock head%}
{%block title%}
{{mess.name}}
{%endblock title%}
{%block content%}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-7 col-md-7 m-2 details">
            <h1>{{mess.name}}</h1>
            <h6>{{mess.address}} </h6>
            <hr>
            <div class="mess-details m-3 p-3">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-6">

                        <h6><i class="fa-solid fa-people-group"></i> {{mess.students_num}} students</h6>
                        <h6><i class="fa-solid fa-location-dot"></i> {{mess.get_region_display}}</h6>
                        <h6><i class="fa-solid fa-house"></i> {{mess.get_structure_display}}</h6>
                        <!-- <hr> -->
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-6">

                        <h6><i class="fa-solid fa-venus-mars"></i> {{mess.get_gender_display}}</h6>
                        <h6><i class="fas fa-utensils"></i> {{mess.get_meal_system_display}}</h6>
                        <h6><i class="fas fa-road"></i> {{mess.distance}} meter from Main Gate</h6>
                    </div>
                </div>
            </div>
            <div class="row room-details m-3">
                <div class="col-sm-12">
                    <h3>Rooms of {{mess.name}}</h3>
                </div>
                <div class="col-sm-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Room No.</th>
                                <th scope="col">Floor</th>
                                <th scope="col">Beds</th>
                                <th scope="col">Price</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for room in rooms %}
                            <tr>
                                <td> <a href="{% url 'room_details' room.id %}">{{room.room_no}}</a></td>
                                <td>{{room.floor}}</td>
                                <td>{{room.bed_num}}</td>
                                <td>{{room.price}}</td>
                                <td>{% if room.status%}
                                    <span style="color: rgb(0, 126, 82);">Available</span>
                                    {% else %}
                                    <span style="color: rgb(219, 56, 15);">Unvailable</span>
                                    {% endif%}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>

            </div>
        </div>

        <div class="col-lg-4 col-md-4 m-2 profile text-center">
            <h2>Owner details</h2>
            <hr>
            <img class="propic" src="{{mess.owner.user.profile_pic.url}}" alt="Profile Picture">
            <a href="{% url 'oprofile' mess.owner.user.id %}"><h3>{{mess.owner.user.name}}</h3> </a> 
          
            <a href="mailto:{{mess.owmer.email}}">
                <h6><i class="fa-solid fa-envelope"></i> {{mess.owner.user.email}}</h6>
            </a>

            <h6><i class="fas fa-phone"></i> {{mess.owner.user.number}}</h6>

        </div>
    </div>
    <!-- ======================== -->
    <!-- for comments -->
    <div class="row comments my-5 p-3">
        <h2>Reviews:</h2>
        <div class="col-sm-12">
            {% for review in reviews %}
            <div class="row my-1">
                <div class="product-comment col-lg-12 py-1">
                    <span class='username'>
                        {{review.reviewer.name}}
                    </span> <br>
                    {{review.content}}
                    <hr>

                </div>

            </div>
            {%endfor%}
        </div>
    </div>
    <!-- new comment -->
    <div class="row">
        <div class="col-lg-12 text-center pt-3">
            <h4>Leave a Review:</h4>
        </div>

        <div class="col-sm-12">
            <form action="{% url 'review' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="mess_id" value="{{mess.id}}">
                <input type="hidden" name="user_id" value="{{user.id}}">
                <div class="form-group">
                    <textarea class="form-control" name="content" id="text" rows="3" required></textarea>
                </div>
                <button type="submit" class="btn btn-outline-success my-3">Submit</button>
            </form>
        </div>
    </div>
</div>
{%endblock content%}

templates/oprofile.html
{% extends 'base.html'%}
{% load static %}


{%block head%}

<link type="text/css" rel="stylesheet" href="{% static 'css/ohome.css' %}" />
{%endblock head%}

{% block title %}Owner Home{% endblock title%}

{% block content %}
<div class="container-fluid m-10">
    <div class="row m-3">
        <div class="col-lg-3 col-md-12 m-2 profile text-center">
            <h3>Owner</h3>
            <hr>
            <img class="propic" src="{{owner.user.profile_pic.url}}" alt="Profile Picture">
            <h3>{{owner.user.name}}</h3>

            <h6><i class="fa-solid fa-envelope"></i> {{owner.user.email}}</h6>
            <h6><i class="fas fa-phone"></i> {{owner.user.number}}</h6>
            <!-- <a class = "btn btn-outline-success" href="{%url 'add_mess' user.id %}">Add Mess</a>
            <a class = "btn btn-outline-info" href="{%url 'edit_oprofile' user.id %}">Update Profile</a> -->

        </div>
        
        <div class="col-lg-8 col-md-12  details">


            {% for mess in messes %}
            <div class="row my-2 one-mess py-3">
                <div class="col">
                    <h1>{{mess.name}}</h1>  
                    <h6>{{mess.address}} </h6>
                    <!-- <a class = "btn btn-outline-success" href="{%url 'edit_mess' mess.id %}"> Update Mess</a>
                    <a class = "btn btn-outline-danger" href="{%url 'delete_mess' mess.id %}"> Delete Mess</a> -->
                    
                    
                    
                    <!-- <hr> -->
                    <div class="mess-details p-3 my-3 mx-1">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-6">

                                <h6><i class="fa-solid fa-people-group"></i> {{mess.students_num}} students</h6>
                                <h6><i class="fa-solid fa-location-dot"></i> {{mess.get_region_display}}</h6>
                                <h6><i class="fa-solid fa-house"></i> {{mess.get_structure_display}}</h6>
                                <!-- <hr> -->
                               
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-6">

                                <h6><i class="fa-solid fa-venus-mars"></i> {{mess.get_gender_display}}</h6>
                                <h6><i class="fas fa-utensils"></i> {{mess.get_meal_system_display}}</h6>
                                <h6><i class="fas fa-road"></i> {{mess.distance}} meter from Main Gate</h6>
                            </div>
                        </div>
                    </div>
                    

                    <div class="row room-details mx-1">
                        <div class="col-sm-12">
                            <h3>Rooms of {{mess.name}}</h3>
                        </div>
                        <div class="col-sm-12">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Room No.</th>
                                        <th scope="col">Floor</th>
                                        <th scope="col">Beds</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">Status</th>
                                        <!-- <th scope="col">Update</th>
                                        <th scope="col">Delete</th> -->
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for room in rooms %}
                                    {%if room.mess == mess %}
                                    <tr>
                                        <td>{{room.room_no}}</td>
                                        <td>{{room.floor}}</td>
                                        <td>{{room.bed_num}}</td>
                                        <td>{{room.price}}</td>
                                        <td>{% if room.status%}
                                            <span style="color: rgb(0, 126, 82);">Available</span>
                                            {% else %}
                                            <span style="color: rgb(219, 56, 15);">Unvailable</span>
                                            {% endif%}
                                        </td>
                                        <!-- <td><a href="{% url 'update_room' room.id%}">Update</a> </td>
                                        <td><a class = 'delete' href="{% url 'delete_room' room.id%}">Delete</a> </td> -->
                                    </tr>
                                    {%endif%}
                                    {% endfor %}
                                </tbody>
                            </table>
                            
        
                        </div>

                        <!-- <div class="col">
                            <a class = "btn btn-outline-info" href="{%url 'add_room' mess.id %}">Add Room</a>
                        </div> -->
        
                    </div>
               
                </div> <!-- endcol -->


                
            </div> <!-- endrow -->
            {%endfor%}
            
        </div>
       
    </div>


</div>

{% endblock content %}

templates/room_details.html
{%extends 'base.html'%}
{% load static%}

{%block title%}
Room Details
{%endblock title%}

{%block head%}



<link type="text/css" rel="stylesheet" href="{% static 'css/details.css'  %}" />
{%endblock head%}



{%block content%}


<div class="container">
    <div class="col-lg-8 border p-3 main-section bg-white">
        <div class="row hedding m-0 pl-3 pt-0 pb-3">
            <a href="/mess/{{room.mess.id}}">
                <h2>{{room.mess.name }}</h2>
            </a>
        </div>
        <div class="row m-0">
            <div class="col-lg-4 left-side-product-box pb-3">
                <div class="row">
                    <div class="col">
                       <a href="{{room.image1.url}}"> <img src="{{room.image1.url}}" class="border p-3"></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <a href="{{room.image2.url}}"> <img src="{{room.image2.url}}" class="border "></a>
                    </div>
                    <div class="col">
                        <a href="{{room.image3.url}}"> <img src="{{room.image3.url}}" class="border "></a>
                    </div>
                </div>
                <!-- <img src="{{room.image1.url}}" class="border p-3">
                <span class="sub-img">
                    <img src="{{room.image2.url}}" class="border p-2">
                    <img src="{{room.image3.url}}" class="border p-2">

                </span> -->
            </div>
            <div class="col-lg-8">
                <div class="right-side-pro-detail border p-3 m-0">
                    <div class="row">
                        <div class="col-lg-12">
                            <span></span>
                            <p class="m-0 p-0">Room No. {{room.room_no}}</p>
                        </div>
                        <div class="col-lg-12">
                            <p class="m-0 p-0 price-pro">৳{{room.price}} per bed</p>
                            <hr class="p-0 m-0">
                        </div>
                        <div class="col-lg-12 pt-2">
                            <h5>Room Detail:</h5>
                            <div class="row">
                                <div class="col left-col">

                                    <span class="">{{room.bed_num}} beds</span> <br>

                                    <span class="">{{room.floor}} Floor</span> <br>
                                    <span class="region">For {{room.mess.get_gender_display}} </span> <br>
                                    {% if room.status%}
                                    <span style="color: rgb(0, 126, 82);">Available</span> <br>
                                    {% else %}
                                    <span style="color: rgb(219, 56, 15);">Unvailable</span> <br>
                                    {% endif%}
                                </div>
                                <div class="col ">


                                    <span class="">{{room.mess.get_region_display}} area</span> <br>
                                    <span class="">Meal System: {{room.mess.get_meal_system_display}}</span> <br>


                                    <span>Structure: {{room.mess.get_structure_display}}</span> <br>

                                    <span>{{room.mess.students_num}} students</span> <br>
                                    <span>{{room.mess.distance}} meters</span> <br>
                                </div>
                            </div>
                            <!-- -->
                        </div>



                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center pt-3">
                <h4>Comments:</h4>
                <!-- TODO: Differentiate Mess Comments and Room Comments -->
            </div>
        </div>
        {% for comment in comments %}
        <div class="row my-1">
            <div class="room-comment col-lg-12 py-1">
                <span class='username'>{{comment.commenter.name}}</span> <br>
                {{comment.content}}
                <hr>

            </div>

        </div>
        {%endfor%}
        <!-- new comment -->
    <div class="row">
        <div class="col-lg-12 text-center pt-3">
            <h4>Leave a comment:</h4>
        </div>

        <div class="col-sm-12">
            <form action="{% url 'comment' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="room_id" value="{{room.id}}">
                <input type="hidden" name="user_sid" value="{{user.id}}">
                <div class="form-group">
                    <textarea class="form-control" name="comment" id="text" rows="3" required></textarea>
                </div>
                <button type="submit" class="btn btn-outline-success my-3">Submit</button>
            </form>
        </div>
    </div>
    </div>
</div>
{%endblock content%}

templates/sprofile.html
{%extends 'base.html'%}
{%load static%}
{%block head%}

{%endblock head%}
{%block title%}
Student Profile
{%endblock title%}
{%block content%}

<div class="container-fluid">
    <div class="row">
        <div class="col">
            {{student.sid}}
            {{student.user.name}}
            {{student.sid}}
        </div>
    </div>
</div>
{%endblock content%}